export const LOGIN_PATH = "/login";

// Benchmark Suites Configuration
export const BENCHMARK_SUITES = {
  MMLU: {
    id: "mmlu",
    name: "MMLU",
    fullName: "Massive Multitask Language Understanding",
    description: "Tests knowledge across 57 diverse subjects including STEM, humanities, and social sciences",
    category: "language_understanding",
    totalQuestions: 15242,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/cais/mmlu",
    estimatedTime: "4-6 hours",
    costPerTest: "$2-5",
    icon: "📚",
    color: "#3b82f6",
  },
  GPQA: {
    id: "gpqa",
    name: "GPQA",
    fullName: "Graduate-Level Google-Proof Q&A",
    description: "Graduate-level questions in biology, physics, and chemistry that are difficult to answer without domain expertise",
    category: "reasoning",
    totalQuestions: 4384,
    difficulty: "expert",
    datasetUrl: "https://huggingface.co/datasets/Idavidrein/gpqa",
    estimatedTime: "2-3 hours",
    costPerTest: "$3-8",
    icon: "🎓",
    color: "#8b5cf6",
  },
  HumanEval: {
    id: "humaneval",
    name: "HumanEval",
    fullName: "Human Evaluation of Code Generation",
    description: "165 hand-written programming problems to evaluate code generation capabilities",
    category: "programming",
    totalQuestions: 165,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/openai_humaneval",
    estimatedTime: "1-2 hours",
    costPerTest: "$1-3",
    icon: "💻",
    color: "#10b981",
  },
  MATH: {
    id: "math",
    name: "MATH",
    fullName: "Mathematics Benchmark",
    description: "12,500 competition-level mathematics problems requiring step-by-step reasoning",
    category: "mathematics",
    totalQuestions: 12500,
    difficulty: "expert",
    datasetUrl: "https://huggingface.co/datasets/hendrycks/math",
    estimatedTime: "3-5 hours",
    costPerTest: "$2-6",
    icon: "🔢",
    color: "#f59e0b",
  },
  ARC: {
    id: "arc",
    name: "ARC",
    fullName: "AI2 Reasoning Challenge",
    description: "14,000 multiple-choice science questions requiring reasoning and knowledge",
    category: "reasoning",
    totalQuestions: 14000,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/ai2_arc",
    estimatedTime: "2-4 hours",
    costPerTest: "$1-4",
    icon: "🧠",
    color: "#ef4444",
  },
  HellaSwag: {
    id: "hellaswag",
    name: "HellaSwag",
    fullName: "Hard Everyday Language Inference",
    description: "70,000 multiple-choice questions about common sense and everyday situations",
    category: "instruction_following",
    totalQuestions: 70000,
    difficulty: "medium",
    datasetUrl: "https://huggingface.co/datasets/Rowan/hellaswag",
    estimatedTime: "3-5 hours",
    costPerTest: "$1-3",
    icon: "💭",
    color: "#06b6d4",
  },
  LAMBADA: {
    id: "lambada",
    name: "LAMBADA",
    fullName: "Language Modeling Benchmark for Discourse",
    description: "10,000 questions requiring understanding of narrative and discourse context",
    category: "language_understanding",
    totalQuestions: 10000,
    difficulty: "medium",
    datasetUrl: "https://huggingface.co/datasets/EleutherAI/lambada",
    estimatedTime: "1-2 hours",
    costPerTest: "$0.5-2",
    icon: "📖",
    color: "#ec4899",
  },
  TruthfulQA: {
    id: "truthfulqa",
    name: "TruthfulQA",
    fullName: "Truthful Question Answering",
    description: "817 questions testing whether models answer truthfully vs. defaulting to common misconceptions",
    category: "safety",
    totalQuestions: 817,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/truthfulqa/truthful_qa",
    estimatedTime: "30-45 minutes",
    costPerTest: "$0.5-1",
    icon: "✅",
    color: "#14b8a6",
  },
  GSM8K: {
    id: "gsm8k",
    name: "GSM8K",
    fullName: "Grade School Math 8K",
    description: "8,500 grade school math word problems requiring multi-step reasoning",
    category: "mathematics",
    totalQuestions: 8500,
    difficulty: "medium",
    datasetUrl: "https://huggingface.co/datasets/openai/gsm8k",
    estimatedTime: "1-2 hours",
    costPerTest: "$0.5-2",
    icon: "🎒",
    color: "#a855f7",
  },
  BBH: {
    id: "bbh",
    name: "BBH",
    fullName: "Big Bench Hard",
    description: "23 challenging tasks from Big Bench where LLMs significantly underperform humans",
    category: "reasoning",
    totalQuestions: 3000,
    difficulty: "expert",
    datasetUrl: "https://huggingface.co/datasets/lukaemon/bbh",
    estimatedTime: "2-3 hours",
    costPerTest: "$2-5",
    icon: "🏔️",
    color: "#f97316",
  },
  MGSM: {
    id: "mgsm",
    name: "MGSM",
    fullName: "Multilingual Grade School Math",
    description: "GSM8K translated to 10 languages for multilingual evaluation",
    category: "mathematics",
    totalQuestions: 8500,
    difficulty: "medium",
    datasetUrl: "https://huggingface.co/datasets/google-research-datasets/mgsm",
    estimatedTime: "1-2 hours",
    costPerTest: "$1-3",
    icon: "🌍",
    color: "#06b6d4",
  },
  XWINOGrad: {
    id: "xwinogradv",
    name: "XWINOGrad",
    fullName: "Multilingual Winograd Schema Challenge",
    description: "Winograd schema challenge in 10 languages testing pronoun resolution",
    category: "language_understanding",
    totalQuestions: 5000,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/x-winograd/x-winograd",
    estimatedTime: "1-2 hours",
    costPerTest: "$0.5-2",
    icon: "🔄",
    color: "#8b5cf6",
  },
  COMMONSENSE_QA: {
    id: "commonsense_qa",
    name: "CommonsenseQA",
    fullName: "Commonsense Question Answering",
    description: "12,000 multiple-choice questions requiring commonsense reasoning",
    category: "reasoning",
    totalQuestions: 12000,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/commonsense_qa",
    estimatedTime: "1-2 hours",
    costPerTest: "$1-2",
    icon: "🎯",
    color: "#10b981",
  },
  SQuAD: {
    id: "squad",
    name: "SQuAD",
    fullName: "Stanford Question Answering Dataset",
    description: "100,000+ reading comprehension questions based on Wikipedia articles",
    category: "language_understanding",
    totalQuestions: 107785,
    difficulty: "medium",
    datasetUrl: "https://huggingface.co/datasets/squad",
    estimatedTime: "2-3 hours",
    costPerTest: "$1-3",
    icon: "📰",
    color: "#3b82f6",
  },
  NATURAL_QUESTIONS: {
    id: "natural_questions",
    name: "Natural Questions",
    fullName: "Natural Questions Dataset",
    description: "307,000 questions from real Google searches with Wikipedia passages",
    category: "language_understanding",
    totalQuestions: 307000,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/natural_questions",
    estimatedTime: "4-6 hours",
    costPerTest: "$3-8",
    icon: "❓",
    color: "#f59e0b",
  },
  WINOGRANDE: {
    id: "winogrande",
    name: "WinoGrande",
    fullName: "WinoGrande Schema Challenge",
    description: "44,000 pronoun resolution problems testing commonsense reasoning",
    category: "reasoning",
    totalQuestions: 44000,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/winogrande",
    estimatedTime: "2-3 hours",
    costPerTest: "$1-3",
    icon: "🔗",
    color: "#8b5cf6",
  },
  RACE: {
    id: "race",
    name: "RACE",
    fullName: "Reading Comprehension from Examinations",
    description: "100,000 reading comprehension questions from English exams",
    category: "language_understanding",
    totalQuestions: 100000,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/race",
    estimatedTime: "2-3 hours",
    costPerTest: "$1-3",
    icon: "📝",
    color: "#ec4899",
  },
  NATURALQUESTIONS_OPEN: {
    id: "nq_open",
    name: "NQ Open",
    fullName: "Natural Questions Open",
    description: "Open-ended version of Natural Questions with 79,000 questions",
    category: "language_understanding",
    totalQuestions: 79000,
    difficulty: "expert",
    datasetUrl: "https://huggingface.co/datasets/natural_questions",
    estimatedTime: "3-4 hours",
    costPerTest: "$2-5",
    icon: "🌐",
    color: "#06b6d4",
  },
  TOXIGEN: {
    id: "toxigen",
    name: "ToxiGen",
    fullName: "Toxicity Generation Benchmark",
    description: "11,000 toxic and non-toxic text examples for safety evaluation",
    category: "safety",
    totalQuestions: 11000,
    difficulty: "medium",
    datasetUrl: "https://huggingface.co/datasets/toxigen/toxigen_data",
    estimatedTime: "1-2 hours",
    costPerTest: "$0.5-1",
    icon: "⚠️",
    color: "#ef4444",
  },
  XSQUAD: {
    id: "xsquad",
    name: "XQuAD",
    fullName: "Cross-lingual Question Answering Dataset",
    description: "SQuAD translated to 11 languages for multilingual evaluation",
    category: "language_understanding",
    totalQuestions: 11200,
    difficulty: "hard",
    datasetUrl: "https://huggingface.co/datasets/xquad",
    estimatedTime: "1-2 hours",
    costPerTest: "$1-2",
    icon: "🌏",
    color: "#10b981",
  },
}

// Scoring Rubrics
export const SCORING_RUBRICS = {
  ACCURACY: {
    name: "Accuracy",
    description: "Percentage of correct answers",
    weight: 0.4,
    formula: "(correct_answers / total_questions) * 100",
  },
  PRECISION: {
    name: "Precision",
    description: "Ratio of true positives to all positive predictions",
    weight: 0.15,
    formula: "true_positives / (true_positives + false_positives)",
  },
  RECALL: {
    name: "Recall",
    description: "Ratio of true positives to all actual positives",
    weight: 0.15,
    formula: "true_positives / (true_positives + false_negatives)",
  },
  F1_SCORE: {
    name: "F1 Score",
    description: "Harmonic mean of precision and recall",
    weight: 0.15,
    formula: "2 * (precision * recall) / (precision + recall)",
  },
  LATENCY: {
    name: "Latency",
    description: "Average response time in milliseconds",
    weight: 0.1,
    formula: "sum(response_times) / number_of_responses",
  },
  EFFICIENCY: {
    name: "Efficiency",
    description: "Tokens generated per second",
    weight: 0.05,
    formula: "total_tokens_generated / total_time_seconds",
  },
}

// Performance Thresholds
export const PERFORMANCE_THRESHOLDS = {
  EXCELLENT: { min: 90, color: "#10b981", label: "Excellent" },
  GOOD: { min: 80, max: 89, color: "#3b82f6", label: "Good" },
  ACCEPTABLE: { min: 70, max: 79, color: "#f59e0b", label: "Acceptable" },
  POOR: { min: 60, max: 69, color: "#ef4444", label: "Poor" },
  CRITICAL: { max: 59, color: "#dc2626", label: "Critical" },
}

// Reference Model Scores (for comparison)
export const REFERENCE_MODELS = {
  GPT4: {
    name: "GPT-4",
    mmlu: 86,
    gpqa: 83,
    humaneval: 90,
    math: 82,
    arc: 96,
    hellaswag: 95,
    lambada: 92,
    truthfulqa: 79,
    gsm8k: 92,
    bbh: 84,
  },
  CLAUDE3_OPUS: {
    name: "Claude 3 Opus",
    mmlu: 88,
    gpqa: 85,
    humaneval: 84,
    math: 80,
    arc: 94,
    hellaswag: 93,
    lambada: 90,
    truthfulqa: 81,
    gsm8k: 95,
    bbh: 86,
  },
  LLAMA2_70B: {
    name: "Llama 2 70B",
    mmlu: 82,
    gpqa: 72,
    humaneval: 81,
    math: 56,
    arc: 85,
    hellaswag: 88,
    lambada: 84,
    truthfulqa: 75,
    gsm8k: 78,
    bbh: 65,
  },
  MISTRAL_LARGE: {
    name: "Mistral Large",
    mmlu: 84,
    gpqa: 78,
    humaneval: 85,
    math: 68,
    arc: 88,
    hellaswag: 90,
    lambada: 86,
    truthfulqa: 77,
    gsm8k: 82,
    bbh: 72,
  },
  DEEPSEEK_67B: {
    name: "DeepSeek 67B",
    mmlu: 85,
    gpqa: 80,
    humaneval: 87,
    math: 75,
    arc: 92,
    hellaswag: 92,
    lambada: 88,
    truthfulqa: 78,
    gsm8k: 88,
    bbh: 79,
  },
}
